# Generated by Django 3.2 on 2021-05-03 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_to_start_game", models.IntegerField(default=7870)),
                ("owner_id", models.CharField(default="", max_length=124)),
                ("joiner_id", models.CharField(default="", max_length=124)),
                ("owner_progress", models.IntegerField(default=0)),
                ("joiner_progress", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_game_seconds", models.IntegerField(default=0)),
                ("last_game_mistake", models.IntegerField(default=0)),
                ("last_game_point", models.IntegerField(default=0)),
                ("game_progress", models.IntegerField(default=0)),
                ("opponent_game_progress", models.IntegerField(default=0)),
                ("is_game_owner", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("game_playing", models.ManyToManyField(blank=True, to="api.Game")),
                (
                    "user_prof",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
