# Generated by Django 3.2 on 2021-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210503_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opponent_game_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='id_to_start_game',
            field=models.IntegerField(default=8359),
        ),
    ]
