# Generated by Django 3.2 on 2021-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210504_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joiner_id',
            field=models.CharField(default='', max_length=124),
        ),
        migrations.AddField(
            model_name='game',
            name='joiner_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='owner_id',
            field=models.CharField(default='', max_length=124),
        ),
        migrations.AddField(
            model_name='game',
            name='owner_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_game_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='id_to_start_game',
            field=models.IntegerField(default=5376),
        ),
    ]
